"""add player birth date

Revision ID: 0c0d9e261dd7
Revises: 73b5151f0abb
Create Date: 2026-09-09 23:28:11.288160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c0d9e261dd7'
down_revision: Union[str, Sequence[str], None] = '73b5151f0abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('birth_date', sa.Date(), nullable=True, comment="Date of birth, from GET /v1/player/{id}/landing. Feeds the aging curve: a player's age at a given season is what lets the model separate a decline that is age from a decline that is noise. NULL until the bios sync runs, and for anyone the endpoint has no record of."))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'birth_date')
    # ### end Alembic commands ###
