"""allow a season without conferences

Revision ID: 73b5151f0abb
Revises: a086bc1dbe9b
Create Date: 2026-09-09 13:35:35.837398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b5151f0abb'
down_revision: Union[str, Sequence[str], None] = 'a086bc1dbe9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nhl_teams', 'conference',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               comment="Conference name: 'Eastern' or 'Western'. NULL for a season played without conferences - 2020-21 used four temporary divisions and had none. Reflects the most recently synced season, not any particular one.",
               existing_comment="Conference name: 'Eastern' or 'Western'.")
    op.alter_column('nhl_teams', 'division',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               comment='Division name: Atlantic, Metropolitan, Central, or Pacific - or the temporary 2020-21 names (Scotia North, MassMutual East, Discover Central, Honda West), which is why this is wider than 16 characters. Reflects the most recently synced season.',
               existing_comment='Division name: Atlantic, Metropolitan, Central, or Pacific.',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nhl_teams', 'division',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               comment='Division name: Atlantic, Metropolitan, Central, or Pacific.',
               existing_comment='Division name: Atlantic, Metropolitan, Central, or Pacific - or the temporary 2020-21 names (Scotia North, MassMutual East, Discover Central, Honda West), which is why this is wider than 16 characters. Reflects the most recently synced season.',
               existing_nullable=False)
    op.alter_column('nhl_teams', 'conference',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               comment="Conference name: 'Eastern' or 'Western'.",
               existing_comment="Conference name: 'Eastern' or 'Western'. NULL for a season played without conferences - 2020-21 used four temporary divisions and had none. Reflects the most recently synced season, not any particular one.")
    # ### end Alembic commands ###
