"""create nhl warehouse and yahoo config tables

Revision ID: a086bc1dbe9b
Revises:
Create Date: 2026-09-09 12:19:31.377420

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a086bc1dbe9b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "league_settings",
        sa.Column(
            "league_key",
            sa.String(length=32),
            nullable=False,
            comment="Yahoo league key, '{game_key}.l.{league_id}' (e.g. '465.l.12345'). PK. The game key changes every season, so this is season-unique.",
        ),
        sa.Column(
            "league_id",
            sa.String(length=16),
            nullable=False,
            comment="Numeric league id from the league URL, without the game key.",
        ),
        sa.Column(
            "season",
            sa.Integer(),
            nullable=False,
            comment="NHL season start year as Yahoo reports it (e.g. 2026 for 2026-27).",
        ),
        sa.Column("name", sa.String(length=128), nullable=False, comment="League display name."),
        sa.Column("num_teams", sa.Integer(), nullable=False, comment="Number of fantasy teams."),
        sa.Column(
            "scoring_type",
            sa.String(length=16),
            nullable=False,
            comment="Yahoo scoring type: 'headpoint' = head-to-head points, 'head' = head-to-head categories, 'point' = season points, 'roto'. This project assumes a points-based type; a category league would need different value logic downstream.",
        ),
        sa.Column(
            "raw",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Full unmodified settings payload from Yahoo, so a later question about a setting we did not normalize can be answered without a re-sync.",
        ),
        sa.Column(
            "synced_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When this row was last read from Yahoo, UTC.",
        ),
        sa.PrimaryKeyConstraint("league_key"),
        comment="One row per Yahoo league season. Source: GET /fantasy/v2/league/{league_key}/settings (fantasysports.yahooapis.com).",
    )
    op.create_table(
        "nhl_teams",
        sa.Column(
            "abbrev",
            sa.String(length=3),
            nullable=False,
            comment="3-letter NHL team abbreviation (e.g. TOR). PK; changes on franchise relocation (e.g. ARI->UTA), which would need a data migration.",
        ),
        sa.Column(
            "name",
            sa.String(length=64),
            nullable=False,
            comment="Full team name, English locale (e.g. 'Toronto Maple Leafs').",
        ),
        sa.Column(
            "conference",
            sa.String(length=16),
            nullable=False,
            comment="Conference name: 'Eastern' or 'Western'.",
        ),
        sa.Column(
            "division",
            sa.String(length=16),
            nullable=False,
            comment="Division name: Atlantic, Metropolitan, Central, or Pacific.",
        ),
        sa.Column(
            "nhl_team_id",
            sa.Integer(),
            nullable=True,
            comment="NHL numeric team id (e.g. TOR=10). NULL until schedule sync backfills it; the standings endpoint does not provide it.",
        ),
        sa.PrimaryKeyConstraint("abbrev"),
        comment="NHL teams. Source: GET /v1/standings/now (api-web.nhle.com); numeric id backfilled from /v1/club-schedule-season.",
    )
    op.create_table(
        "league_roster_positions",
        sa.Column(
            "league_key", sa.String(length=32), nullable=False, comment="FK league_settings."
        ),
        sa.Column(
            "position",
            sa.String(length=8),
            nullable=False,
            comment="Slot code: C, LW, RW, D, G, BN, IR+, and flex codes like Util. Part of PK.",
        ),
        sa.Column(
            "count", sa.Integer(), nullable=False, comment="How many of this slot each roster has."
        ),
        sa.Column(
            "is_starting",
            sa.Boolean(),
            nullable=False,
            comment="True for slots that score (C/LW/RW/D/G); False for BN and IR+.",
        ),
        sa.ForeignKeyConstraint(
            ["league_key"],
            ["league_settings.league_key"],
        ),
        sa.PrimaryKeyConstraint("league_key", "position"),
        comment="Roster slots and counts for a league (C x2, D x4, BN x5, ...), from Yahoo settings roster_positions. Used by the draft export to size the pool.",
    )
    op.create_table(
        "league_stat_categories",
        sa.Column(
            "league_key", sa.String(length=32), nullable=False, comment="FK league_settings."
        ),
        sa.Column(
            "stat_id",
            sa.Integer(),
            nullable=False,
            comment="Yahoo's numeric stat id (e.g. 1 = Goals). Part of PK.",
        ),
        sa.Column(
            "name",
            sa.String(length=64),
            nullable=False,
            comment="Yahoo's full stat name, e.g. 'Power Play Points'.",
        ),
        sa.Column(
            "display_name",
            sa.String(length=16),
            nullable=False,
            comment="Yahoo's abbreviation, e.g. 'PPP', 'SHP', 'HIT', 'BLK'.",
        ),
        sa.Column(
            "position_type",
            sa.String(length=1),
            nullable=False,
            comment="'P' = skater stat, 'G' = goalie stat.",
        ),
        sa.Column(
            "modifier",
            sa.Float(),
            nullable=False,
            comment="Fantasy points per unit of this stat. Can be negative (goals against is -1.5 in this league).",
        ),
        sa.Column(
            "source_column",
            sa.String(length=32),
            nullable=True,
            comment="Warehouse column this category reads, as 'table.column' (e.g. 'skater_game_logs.hits'). NULL means the warehouse cannot serve this category; hockey/scoring/ raises at config-load time rather than silently scoring it as zero.",
        ),
        sa.ForeignKeyConstraint(
            ["league_key"],
            ["league_settings.league_key"],
        ),
        sa.PrimaryKeyConstraint("league_key", "stat_id"),
        comment="Scoring categories and point modifiers for a league, from Yahoo's settings stat_categories + stat_modifiers. Drives hockey/scoring/.",
    )
    op.create_table(
        "nhl_games",
        sa.Column(
            "nhl_game_id",
            sa.BigInteger(),
            nullable=False,
            comment="NHL game id (e.g. 2025020001: season 2025, type 02, game 0001). PK.",
        ),
        sa.Column(
            "date",
            sa.Date(),
            nullable=False,
            comment="Game calendar date (Eastern Time) from the API gameDate.",
        ),
        sa.Column(
            "start_time_utc",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Scheduled puck drop in UTC (API startTimeUTC). Used for lineup locking. NULL only for rows synced before this column existed; backfilled by re-running the schedule sync.",
        ),
        sa.Column(
            "season",
            sa.Integer(),
            nullable=False,
            comment="NHL season as start+end year int (e.g. 20252026).",
        ),
        sa.Column(
            "game_type",
            sa.Integer(),
            nullable=False,
            comment="NHL game type: 2 = regular season, 3 = playoffs. Preseason (1) is intentionally not synced.",
        ),
        sa.Column(
            "home_team_abbrev",
            sa.String(length=3),
            nullable=False,
            comment="FK nhl_teams.abbrev, home side.",
        ),
        sa.Column(
            "away_team_abbrev",
            sa.String(length=3),
            nullable=False,
            comment="FK nhl_teams.abbrev, away side.",
        ),
        sa.Column(
            "game_state",
            sa.String(length=16),
            nullable=False,
            comment="NHL game state. OFF/FINAL = completed (only these get game logs); FUT = scheduled. Other live states may appear transiently.",
        ),
        sa.Column(
            "home_score",
            sa.Integer(),
            nullable=True,
            comment="Final home goals. NULL until the game is played.",
        ),
        sa.Column(
            "away_score",
            sa.Integer(),
            nullable=True,
            comment="Final away goals. NULL until the game is played.",
        ),
        sa.ForeignKeyConstraint(
            ["away_team_abbrev"],
            ["nhl_teams.abbrev"],
        ),
        sa.ForeignKeyConstraint(
            ["home_team_abbrev"],
            ["nhl_teams.abbrev"],
        ),
        sa.PrimaryKeyConstraint("nhl_game_id"),
        comment="NHL games, regular season and playoffs only. Source: GET /v1/club-schedule-season/{team}/{season}.",
    )
    op.create_index(op.f("ix_nhl_games_date"), "nhl_games", ["date"], unique=False)
    op.create_index(op.f("ix_nhl_games_season"), "nhl_games", ["season"], unique=False)
    op.create_table(
        "players",
        sa.Column(
            "nhl_id",
            sa.BigInteger(),
            nullable=False,
            comment="NHL player id (e.g. McDavid=8478402). PK.",
        ),
        sa.Column(
            "first_name",
            sa.String(length=64),
            nullable=False,
            comment="First name. For boxscore stub rows this is an abbreviated initial (e.g. 'C.') until a roster sync fills the full name.",
        ),
        sa.Column(
            "last_name", sa.String(length=64), nullable=False, comment="Last name, English locale."
        ),
        sa.Column(
            "position",
            sa.String(length=2),
            nullable=False,
            comment="Position: C, LW, RW, D, or G. NHL API codes L/R are mapped to LW/RW at ingest (hockey/ingest/mappers.py).",
        ),
        sa.Column(
            "team_abbrev",
            sa.String(length=3),
            nullable=True,
            comment="FK nhl_teams.abbrev. Team whose season roster listed the player; NULL for boxscore stub rows.",
        ),
        sa.Column(
            "status",
            sa.String(length=16),
            nullable=False,
            comment="'active' = on a synced season roster; 'inactive' = seen only in boxscores. NOT injury status; that comes from ESPN into player_injuries.",
        ),
        sa.Column(
            "shoots_catches",
            sa.String(length=1),
            nullable=True,
            comment="Shoots (skaters) or catches (goalies): L or R. NULL for stub rows.",
        ),
        sa.ForeignKeyConstraint(
            ["team_abbrev"],
            ["nhl_teams.abbrev"],
        ),
        sa.PrimaryKeyConstraint("nhl_id"),
        comment="NHL players. Source: GET /v1/roster/{team}/{season}; minimal stub rows are created from boxscores for players absent from season rosters (call-ups, mid-season trades).",
    )
    op.create_table(
        "goalie_game_logs",
        sa.Column(
            "player_id", sa.BigInteger(), nullable=False, comment="FK players.nhl_id. Part of PK."
        ),
        sa.Column(
            "game_id",
            sa.BigInteger(),
            nullable=False,
            comment="FK nhl_games.nhl_game_id. Part of PK.",
        ),
        sa.Column(
            "team_abbrev",
            sa.String(length=3),
            nullable=True,
            comment="FK nhl_teams.abbrev. The team this player dressed for IN THIS GAME, taken from the side of the boxscore they were listed under. Distinct from players.team_abbrev, which is a single current value and is therefore wrong for past seasons and for anyone who was traded. The model needs this to know the opponent and whether the game was played at home. NULL only for rows synced before this column existed.",
        ),
        sa.Column(
            "decision",
            sa.String(length=1),
            nullable=True,
            comment="Game decision: W = win, L = regulation loss, O = overtime/shootout loss. NULL when the goalie played but was not charged with a decision.",
        ),
        sa.Column(
            "wins",
            sa.Integer(),
            nullable=False,
            comment="0 or 1; derived at ingest from decision = 'W'.",
        ),
        sa.Column("goals_against", sa.Integer(), nullable=False, comment="Goals allowed."),
        sa.Column("saves", sa.Integer(), nullable=False, comment="Saves made."),
        sa.Column(
            "shots_against", sa.Integer(), nullable=False, comment="Shots faced (saves + goals)."
        ),
        sa.Column(
            "save_pctg",
            sa.Float(),
            nullable=True,
            comment="Save percentage as a 0-1 fraction (e.g. 0.925). NULL until the player-stats sync fills it from the per-player game-log endpoint; the API may also omit it when no shots were faced.",
        ),
        sa.Column(
            "shutouts",
            sa.Integer(),
            nullable=True,
            comment="0 or 1, per NHL shutout rules (sole goalie, zero goals against, win). NULL until the player-stats sync fills it.",
        ),
        sa.Column(
            "toi_seconds",
            sa.Integer(),
            nullable=False,
            comment="Time on ice in seconds (API 'MM:SS' parsed at ingest).",
        ),
        sa.Column(
            "started", sa.Boolean(), nullable=False, comment="True if this goalie started the game."
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["nhl_games.nhl_game_id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.nhl_id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_abbrev"],
            ["nhl_teams.abbrev"],
        ),
        sa.PrimaryKeyConstraint("player_id", "game_id"),
        comment="Per-goalie per-game stats; only goalies with >0 seconds played get a row. Primary source: GET /v1/gamecenter/{gameId}/boxscore; save_pctg and shutouts filled afterwards from GET /v1/player/{id}/game-log.",
    )
    op.create_index("ix_goalie_game_logs_game", "goalie_game_logs", ["game_id"], unique=False)
    op.create_table(
        "nhl_plays",
        sa.Column(
            "game_id",
            sa.BigInteger(),
            nullable=False,
            comment="FK nhl_games.nhl_game_id. Part of PK.",
        ),
        sa.Column(
            "event_id",
            sa.Integer(),
            nullable=False,
            comment="NHL eventId, unique within a game. Part of PK.",
        ),
        sa.Column(
            "sort_order",
            sa.Integer(),
            nullable=False,
            comment="API sortOrder; the canonical chronological order of events in the game.",
        ),
        sa.Column(
            "period_number",
            sa.Integer(),
            nullable=False,
            comment="Period number (1-3 regulation, 4+ OT, shootout per periodType).",
        ),
        sa.Column(
            "period_type",
            sa.String(length=8),
            nullable=False,
            comment="Period type: REG, OT, or SO (periodDescriptor.periodType).",
        ),
        sa.Column(
            "time_in_period",
            sa.String(length=5),
            nullable=False,
            comment="Elapsed time in the period, 'MM:SS' (as the API reports it).",
        ),
        sa.Column(
            "type_code", sa.Integer(), nullable=False, comment="NHL numeric event type code."
        ),
        sa.Column(
            "type_desc_key",
            sa.String(length=32),
            nullable=False,
            comment="Event type key: faceoff, shot-on-goal, missed-shot, blocked-shot, goal, hit, giveaway, takeaway, penalty, stoppage, period-start/end, game-end, etc.",
        ),
        sa.Column(
            "situation_code",
            sa.String(length=4),
            nullable=True,
            comment="Strength/situation code, e.g. '1551' = 5v5 (away goalie, away skaters, home skaters, home goalie). NULL when the API omits it.",
        ),
        sa.Column(
            "home_team_defending_side",
            sa.String(length=5),
            nullable=True,
            comment="'left' or 'right' — the side the home team defends this event, for normalizing x/y coordinates. NULL on events without it.",
        ),
        sa.Column(
            "x_coord",
            sa.Integer(),
            nullable=True,
            comment="Event x coordinate on the rink (approx -100..100; details.xCoord). NULL for events without a location (stoppages, period boundaries).",
        ),
        sa.Column(
            "y_coord",
            sa.Integer(),
            nullable=True,
            comment="Event y coordinate (approx -42..42; details.yCoord). NULL when absent.",
        ),
        sa.Column(
            "zone_code",
            sa.String(length=1),
            nullable=True,
            comment="Zone of the event relative to the event-owner team: O(ffensive), D(efensive), N(eutral). NULL when absent.",
        ),
        sa.Column(
            "event_owner_team_id",
            sa.Integer(),
            nullable=True,
            comment="NHL numeric team id that 'owns' the event (shooter's/hitter's team, etc.; details.eventOwnerTeamId). NULL when absent.",
        ),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Raw API `details` object for the event (camelCase keys preserved): the per-event-type fields not promoted above — role player ids (shootingPlayerId, scoringPlayerId, assist{1,2}PlayerId, winning/losingPlayerId, hitting/hitteePlayerId, committedBy/drawnByPlayerId), goalieInNetId, shotType, running scores/SOG, clip urls. Empty object for events with no details.",
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["nhl_games.nhl_game_id"],
        ),
        sa.PrimaryKeyConstraint("game_id", "event_id"),
        comment="NHL play-by-play events (analytics dataset). Source: GET /v1/gamecenter/{gameId}/play-by-play. Common fields promoted to columns, per-event fields in JSONB details.",
    )
    op.create_index(
        "ix_nhl_plays_details", "nhl_plays", ["details"], unique=False, postgresql_using="gin"
    )
    op.create_index("ix_nhl_plays_type", "nhl_plays", ["type_desc_key"], unique=False)
    op.create_table(
        "player_crosswalk",
        sa.Column(
            "yahoo_player_id",
            sa.Integer(),
            nullable=False,
            comment="Yahoo's numeric player id. PK.",
        ),
        sa.Column(
            "nhl_id",
            sa.BigInteger(),
            nullable=True,
            comment="FK players.nhl_id. NULL when the name matched nothing or matched several players that the team tiebreak could not separate.",
        ),
        sa.Column(
            "yahoo_name",
            sa.String(length=128),
            nullable=False,
            comment="Full name exactly as Yahoo spells it, for review of misses.",
        ),
        sa.Column(
            "yahoo_team",
            sa.String(length=8),
            nullable=True,
            comment="Yahoo's team abbreviation, used as the tiebreak. NULL if absent.",
        ),
        sa.Column(
            "yahoo_positions",
            sa.String(length=32),
            nullable=False,
            comment="Comma-separated Yahoo eligible positions (e.g. 'C,LW'). Yahoo is the authority on eligibility for this league, not the NHL roster position.",
        ),
        sa.Column(
            "match_method",
            sa.String(length=24),
            nullable=False,
            comment="How the row was decided: 'exact' (one name match), 'team_tiebreak' (several matches, one on the right team), 'ambiguous' (several, none separable) or 'unmatched' (no name match).",
        ),
        sa.Column(
            "synced_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When this row was last refreshed from Yahoo, UTC.",
        ),
        sa.ForeignKeyConstraint(
            ["nhl_id"],
            ["players.nhl_id"],
        ),
        sa.PrimaryKeyConstraint("yahoo_player_id"),
        comment="Yahoo <-> NHL player id mapping, built by normalized-name matching. Rows with nhl_id NULL are deliberate misses kept for review; they are never guessed. See hockey/yahoo/crosswalk.py.",
    )
    op.create_table(
        "player_injuries",
        sa.Column(
            "player_id",
            sa.BigInteger(),
            nullable=False,
            comment="FK players.nhl_id. PK — a player has at most one current injury.",
        ),
        sa.Column(
            "status",
            sa.String(length=32),
            nullable=False,
            comment="ESPN status: 'Out', 'Injured Reserve', 'Day-To-Day', 'Suspension', etc.",
        ),
        sa.Column(
            "injury_type",
            sa.String(length=64),
            nullable=True,
            comment="Body part / injury type (ESPN details.type, e.g. 'Knee'). NULL if absent.",
        ),
        sa.Column(
            "detail",
            sa.String(length=128),
            nullable=True,
            comment="Extra detail (ESPN details.detail, e.g. 'Surgery'). NULL if absent.",
        ),
        sa.Column(
            "return_date",
            sa.String(length=32),
            nullable=True,
            comment="Estimated return (ESPN details.returnDate), stored as given (a date or descriptive text). NULL if absent.",
        ),
        sa.Column(
            "comment",
            sa.String(length=255),
            nullable=True,
            comment="Short human note (ESPN shortComment). NULL if absent.",
        ),
        sa.Column(
            "espn_updated",
            sa.String(length=32),
            nullable=True,
            comment="ESPN's last-updated timestamp for the injury (raw string). NULL if absent.",
        ),
        sa.Column(
            "synced_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When this row was last refreshed from ESPN, UTC (set each sync).",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.nhl_id"],
        ),
        sa.PrimaryKeyConstraint("player_id"),
        comment="Current player injuries from ESPN's unofficial feed (no official NHL source). One row per injured player; refreshed wholesale each sync (recovered players are removed). Matched to players by normalized name + team.",
    )
    op.create_table(
        "skater_game_logs",
        sa.Column(
            "player_id", sa.BigInteger(), nullable=False, comment="FK players.nhl_id. Part of PK."
        ),
        sa.Column(
            "game_id",
            sa.BigInteger(),
            nullable=False,
            comment="FK nhl_games.nhl_game_id. Part of PK.",
        ),
        sa.Column(
            "team_abbrev",
            sa.String(length=3),
            nullable=True,
            comment="FK nhl_teams.abbrev. The team this player dressed for IN THIS GAME, taken from the side of the boxscore they were listed under. Distinct from players.team_abbrev, which is a single current value and is therefore wrong for past seasons and for anyone who was traded. The model needs this to know the opponent and whether the game was played at home. NULL only for rows synced before this column existed.",
        ),
        sa.Column(
            "position",
            sa.String(length=2),
            nullable=True,
            comment="Position actually skated this game (C/LW/RW/D), from the boxscore — game-specific, not the roster's static primary_position (players.position). Drives multi-position eligibility. NULL for rows synced before this column existed; backfilled by re-running the game-log sync. NHL L/R mapped to LW/RW.",
        ),
        sa.Column("goals", sa.Integer(), nullable=False, comment="Goals scored."),
        sa.Column(
            "assists", sa.Integer(), nullable=False, comment="Assists (primary + secondary)."
        ),
        sa.Column("points", sa.Integer(), nullable=False, comment="Points (goals + assists)."),
        sa.Column(
            "plus_minus",
            sa.Integer(),
            nullable=False,
            comment="Plus/minus: even-strength and shorthanded goal differential while on ice.",
        ),
        sa.Column("pim", sa.Integer(), nullable=False, comment="Penalty minutes."),
        sa.Column(
            "ppp",
            sa.Integer(),
            nullable=True,
            comment="Power-play points (PP goals + PP assists). NULL until the player-stats sync fills it from the per-player game-log endpoint; stays NULL for dressed-but-did-not-play rows (0:00 TOI), which that endpoint omits.",
        ),
        sa.Column(
            "shp",
            sa.Integer(),
            nullable=True,
            comment="Shorthanded points (SH goals + SH assists). Same source and NULL semantics as ppp: the boxscore does not carry it, so the player-stats sync fills it from the per-player game-log endpoint. Scored by the Yahoo league, so it is not optional here.",
        ),
        sa.Column("sog", sa.Integer(), nullable=False, comment="Shots on goal."),
        sa.Column("hits", sa.Integer(), nullable=False, comment="Hits delivered."),
        sa.Column("blocks", sa.Integer(), nullable=False, comment="Shots blocked."),
        sa.Column(
            "toi_seconds",
            sa.Integer(),
            nullable=False,
            comment="Time on ice in seconds (API 'MM:SS' parsed at ingest).",
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["nhl_games.nhl_game_id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.nhl_id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_abbrev"],
            ["nhl_teams.abbrev"],
        ),
        sa.PrimaryKeyConstraint("player_id", "game_id"),
        comment="Per-skater per-game stats. Primary source: GET /v1/gamecenter/{gameId}/boxscore (one row per dressed skater); ppp and shp filled afterwards from GET /v1/player/{id}/game-log (the boxscore carries neither). See docs/architecture.md 'Game logs merge two NHL API sources'.",
    )
    op.create_index("ix_skater_game_logs_game", "skater_game_logs", ["game_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_skater_game_logs_game", table_name="skater_game_logs")
    op.drop_table("skater_game_logs")
    op.drop_table("player_injuries")
    op.drop_table("player_crosswalk")
    op.drop_index("ix_nhl_plays_type", table_name="nhl_plays")
    op.drop_index("ix_nhl_plays_details", table_name="nhl_plays", postgresql_using="gin")
    op.drop_table("nhl_plays")
    op.drop_index("ix_goalie_game_logs_game", table_name="goalie_game_logs")
    op.drop_table("goalie_game_logs")
    op.drop_table("players")
    op.drop_index(op.f("ix_nhl_games_season"), table_name="nhl_games")
    op.drop_index(op.f("ix_nhl_games_date"), table_name="nhl_games")
    op.drop_table("nhl_games")
    op.drop_table("league_stat_categories")
    op.drop_table("league_roster_positions")
    op.drop_table("nhl_teams")
    op.drop_table("league_settings")
    # ### end Alembic commands ###
