"""CLI: python -m hockey.calibration [--test-season 20252026] [--pool 40]

Fits on every season before the held-out one, projects it, and reports whether
the intervals hold up. Writes the table to docs/model-card.md so the numbers
live next to the model rather than in a terminal that scrolls away.
"""

import argparse
import logging
from pathlib import Path

import arviz as az

from hockey.calibration.backtest import biggest_misses, prepare_backtest, render, score_backtest
from hockey.db import SessionLocal
from hockey.keepawake import keep_awake
from hockey.model import multi
from hockey.seasons import season_label
from hockey.yahoo.settings import load_scoring_from_yaml

ARTIFACTS = Path("artifacts/calibration")
MODEL_CARD = Path("docs/model-card.md")


def main() -> None:
    parser = argparse.ArgumentParser(prog="python -m hockey.calibration")
    parser.add_argument("--test-season", type=int, default=20252026)
    parser.add_argument("--pool", type=int, default=40)
    parser.add_argument("--draws", type=int, default=500)
    parser.add_argument("--tune", type=int, default=800)
    parser.add_argument("--chains", type=int, default=4)
    parser.add_argument("--opponent", action="store_true", help="keep the opponent term")
    parser.add_argument(
        "--idio-walks",
        nargs="*",
        default=["hits"],
        help="categories that keep their own walk (default: hits). Pass with no names for none.",
    )
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

    with keep_awake("held-out calibration"):
        _main(args)


def _main(args) -> None:
    ARTIFACTS.mkdir(parents=True, exist_ok=True)

    with SessionLocal() as session:
        data, actuals = prepare_backtest(session, args.test_season, args.pool)

    model = multi.build(data, include_opponent=args.opponent, include_idio=tuple(args.idio_walks))
    idata = multi.sample(model, draws=args.draws, tune=args.tune, chains=args.chains)

    divergences = int(idata.sample_stats["diverging"].sum())
    diag = az.summary(idata, var_names=["mu_player", "b_home", "loading"], round_to=4)
    print("\n=== convergence ===")
    print(f"  worst r_hat       {diag['r_hat'].max():.4f}")
    print(f"  lowest bulk ESS   {diag['ess_bulk'].min():.0f}")
    print(f"  divergences       {divergences}")

    scoring = load_scoring_from_yaml()
    result = score_backtest(idata, data, actuals, scoring)
    table = render(result, args.test_season)
    print("\n" + table)

    misses = biggest_misses(result)
    print("\n=== furthest from the projection, in standard deviations ===")
    print(misses.round(1).to_string(index=False))

    MODEL_CARD.parent.mkdir(parents=True, exist_ok=True)
    MODEL_CARD.write_text(
        "# Model card\n\n"
        "Generated by `python -m hockey.calibration`. These are the numbers that\n"
        "decide whether the floor and ceiling this model reports can be quoted.\n\n"
        f"Held-out season: {season_label(args.test_season)}. "
        f"Pool: {len(data.players)} skaters. "
        f"Draws: {args.draws} x {args.chains} chains.\n\n"
        f"Convergence: worst r_hat {diag['r_hat'].max():.4f}, "
        f"lowest bulk ESS {diag['ess_bulk'].min():.0f}, "
        f"{divergences} divergences.\n\n"
        "```\n" + table + "\n```\n\n"
        "## Furthest from the projection\n\n"
        "```\n" + misses.round(1).to_string(index=False) + "\n```\n",
        encoding="utf-8",
    )
    idata.to_netcdf(str(ARTIFACTS / "backtest_trace.nc"))
    print(f"\nwrote {MODEL_CARD} and {ARTIFACTS}/backtest_trace.nc")


if __name__ == "__main__":
    main()
